
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLDB_SERVER}/${MYSQLDB_DATABASE}?useSSL=false&&createDatabaseIfNotExist=true
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create